# Generated by Django 4.2 on 2023-06-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation',
            name='estimation',
            field=models.CharField(max_length=10, verbose_name='Оценка'),
        ),
    ]
