# Generated by Django 4.2 on 2023-06-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0002_alter_estimation_estimation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation',
            name='estimation',
            field=models.IntegerField(verbose_name='Оценка'),
        ),
    ]
